[workspace]
authors = ["Ribelio <f.camachoperezdesevilla@student.maastrichtuniversity.nl>"]
channels = ["conda-forge"]
name = "mangaclub"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.8"
pytest = "*"

[pypi-dependencies]
matplotlib = ">=3.10"
pillow = ">=12.0.0,<13"
numpy = ">=2.3.5,<3"
requests = "*"
pyside6 = "*"

[feature.test.tasks]
test = "python -m pytest"

[environments]
test = ["test"]