[workspace]
authors = ["Ribelio <f.camachoperezdesevilla@student.maastrichtuniversity.nl>"]
channels = ["conda-forge"]
name = "mangaclub"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
gui = "python gui.py"
gen = "python schedule.py"
#python = ">=3.10"

[dependencies]
python = ">=3.14.1,<3.15"


[feature.test]
tasks = {test = "python -m pytest"}
pypi-dependencies = {pytest = "*", pre-commit-uv = "*"}

[feature.lint]
dependencies = {ruff = "*"}
tasks = {ruff = "ruff check ."}


[pypi-dependencies]
pillow = ">=10.0.0"
numpy = ">=1.24"
requests = "*"
pyside6 = "*"


[environments]
# default = ["default"]
test = {features=["test"]}
lint = {features=["lint"]}
