[workspace]
authors = ["Ribelio <f.camachoperezdesevilla@student.maastrichtuniversity.nl>"]
channels = ["conda-forge"]
name = "mangaclub"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pillow = ">=12.0.0,<13"
numpy = ">=2.3.5,<3"
requests = "*"
pyside6 = "*"
pixi-pycharm = ">=0.0.10,<0.0.11"
