[workspace]
authors = ["Ribelio <f.camachoperezdesevilla@student.maastrichtuniversity.nl>"]
channels = ["conda-forge"]
name = "mangaclub"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
gui = "python gui.py"
gen = "python schedule.py"

[dependencies]
python = ">=3.10"

[feature.test.tasks]
test = "python -m pytest"

[feature.test.dependencies]
pytest = "*"
ruff = "*"


[pypi-dependencies]
pillow = ">=10.0.0"
numpy = ">=1.24"
requests = "*"
pyside6 = "*"



[environments]
default = ["default"]
test = ["test","default"]
