[workspace]
authors = ["Ribelio <f.camachoperezdesevilla@student.maastrichtuniversity.nl>"]
channels = ["conda-forge"]
name = "mangaclub"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"

[pypi-dependencies]
pillow = ">=10.0.0"
numpy = ">=1.24"
requests = "*"
pyside6 = "*"

[feature.test.tasks]
test = "python -m pytest"

[feature.test.dependencies]
pytest = "*"

[environments]
default = ["default"]
test = ["default", "test"]
